//! Frozen R61 diagnostic cases. Do not edit after the pre-product hash is recorded.

mod natural_realization_canary_support;

use natural_realization_canary_support::{emit, Case};
use semantic_core_adapters::LanguageCodeIR;

const CASES: &[Case] = &[
    Case {
        id: "R61_D01",
        category: "korean_repair_plan",
        setup: &[],
        query: "Nimbus 캐시 오류를 수리해",
        language: LanguageCodeIR::Korean,
        expected_act: "PLAN_PREVIEW",
        required_fragments: &["Nimbus", "먼저", "수리", "검증", "아직 실행"],
        forbidden_fragments: &["선택 행동", "검증 계획으로 처리"],
        max_chars: 220,
    },
    Case {
        id: "R61_D02",
        category: "english_repair_plan",
        setup: &[],
        query: "Repair the Nimbus cache fault",
        language: LanguageCodeIR::English,
        expected_act: "PLAN_PREVIEW",
        required_fragments: &["Nimbus", "first", "repair", "verify", "not executed"],
        forbidden_fragments: &["selected action", "validated plan"],
        max_chars: 260,
    },
    Case {
        id: "R61_D03",
        category: "korean_investigation_plan",
        setup: &[],
        query: "Atlas 서비스 장애 원인을 조사해",
        language: LanguageCodeIR::Korean,
        expected_act: "PLAN_PREVIEW",
        required_fragments: &["Atlas", "상태", "원인", "확인", "아직 실행"],
        forbidden_fragments: &["진단 실행", "단계"],
        max_chars: 220,
    },
    Case {
        id: "R61_D04",
        category: "english_investigation_plan",
        setup: &[],
        query: "Investigate the Atlas service failure",
        language: LanguageCodeIR::English,
        expected_act: "PLAN_PREVIEW",
        required_fragments: &["Atlas", "state", "cause", "check", "not executed"],
        forbidden_fragments: &["diagnostic execution", "planned operations"],
        max_chars: 260,
    },
    Case {
        id: "R61_D05",
        category: "korean_creation_plan",
        setup: &[],
        query: "Beryl 설정 파일을 만들어",
        language: LanguageCodeIR::Korean,
        expected_act: "PLAN_PREVIEW",
        required_fragments: &["Beryl", "완료 조건", "만든", "검증", "아직 실행"],
        forbidden_fragments: &["선택 행동", "검증 계획"],
        max_chars: 220,
    },
    Case {
        id: "R61_D06",
        category: "english_explanation_plan",
        setup: &[],
        query: "Explain the Ember cache architecture",
        language: LanguageCodeIR::English,
        expected_act: "PLAN_PREVIEW",
        required_fragments: &["Ember", "evidence", "explanation", "not executed"],
        forbidden_fragments: &["synthesize explanation", "communicate result"],
        max_chars: 260,
    },
    Case {
        id: "R61_D07",
        category: "korean_inform_acknowledgement",
        setup: &[],
        query: "현재 CCTV 상태는 오프라인이야",
        language: LanguageCodeIR::Korean,
        expected_act: "INFORM_ACKNOWLEDGEMENT",
        required_fragments: &["CCTV", "오프라인", "말한 내용", "확인된 사실"],
        forbidden_fragments: &["검증 계획"],
        max_chars: 190,
    },
    Case {
        id: "R61_D08",
        category: "english_inform_acknowledgement",
        setup: &[],
        query: "The current API status is offline",
        language: LanguageCodeIR::English,
        expected_act: "INFORM_ACKNOWLEDGEMENT",
        required_fragments: &["API", "offline", "you said", "confirmed fact"],
        forbidden_fragments: &["validated plan"],
        max_chars: 210,
    },
    Case {
        id: "R61_D09",
        category: "korean_feedback",
        setup: &[],
        query: "방금 답변은 핵심을 놓쳤어",
        language: LanguageCodeIR::Korean,
        expected_act: "USER_FEEDBACK",
        required_fragments: &["핵심", "놓쳤"],
        forbidden_fragments: &["감정을", "사용자의 피드백"],
        max_chars: 150,
    },
    Case {
        id: "R61_D10",
        category: "english_affect",
        setup: &[],
        query: "This timeout keeps happening and it is really frustrating",
        language: LanguageCodeIR::English,
        expected_act: "AFFECT_SUPPORT",
        required_fragments: &["frustrating", "check"],
        forbidden_fragments: &["authorized a change", "emotion"],
        max_chars: 190,
    },
    Case {
        id: "R61_D11",
        category: "korean_missing_reference",
        setup: &[],
        query: "그거 다시 고쳐",
        language: LanguageCodeIR::Korean,
        expected_act: "CLARIFICATION_REQUEST",
        required_fragments: &["무엇", "가리키는지", "대상"],
        forbidden_fragments: &["resolution", "reference"],
        max_chars: 150,
    },
    Case {
        id: "R61_D12",
        category: "english_missing_reference",
        setup: &[],
        query: "Fix that again",
        language: LanguageCodeIR::English,
        expected_act: "CLARIFICATION_REQUEST",
        required_fragments: &["what", "that", "target"],
        forbidden_fragments: &["resolution", "referent"],
        max_chars: 170,
    },
    Case {
        id: "R61_D13",
        category: "korean_topic_return",
        setup: &["서버를 확인해", "캐시를 확인해"],
        query: "서버 이야기로 돌아가자",
        language: LanguageCodeIR::Korean,
        expected_act: "TOPIC_TRANSITION",
        required_fragments: &["서버", "이야기", "돌아"],
        forbidden_fragments: &["대화 초점 변경", "실행했다는 뜻"],
        max_chars: 150,
    },
    Case {
        id: "R61_D14",
        category: "english_result_absence",
        setup: &["Investigate the Quartz worker fault"],
        query: "What was the result of that?",
        language: LanguageCodeIR::English,
        expected_act: "RESULT_ABSENCE",
        required_fragments: &["Quartz", "no execution result", "plan"],
        forbidden_fragments: &["evidence_absence", "resultreference"],
        max_chars: 220,
    },
    Case {
        id: "R61_D15",
        category: "korean_plan_result_boundary",
        setup: &["백업을 실행해"],
        query: "그건 끝난 거야, 아직 계획만 있는 거야?",
        language: LanguageCodeIR::Korean,
        expected_act: "PLAN_RESULT_STATUS",
        required_fragments: &["백업", "계획", "실행 결과", "아직"],
        forbidden_fragments: &["ACTIVE", "NOT_OBSERVED", "UNAVAILABLE"],
        max_chars: 220,
    },
    Case {
        id: "R61_D16",
        category: "english_plan_result_boundary",
        setup: &["Run the index refresh"],
        query: "Did it finish, or is it only planned?",
        language: LanguageCodeIR::English,
        expected_act: "PLAN_RESULT_STATUS",
        required_fragments: &["index", "plan", "execution result", "not"],
        forbidden_fragments: &["ACTIVE", "NOT_OBSERVED", "UNAVAILABLE"],
        max_chars: 240,
    },
];

fn main() {
    emit("R61-NATURAL-REALIZATION-DIAGNOSTIC", false, CASES);
}
