//! Frozen R45 diagnostic suite for productive grammatical composition.
//!
//! These cases require typed cross-predicate argument sharing rather than
//! whole-sentence dispatch. The shared entity must remain discourse-local and
//! must never grant semantic or execution authority.

mod productive_composition_canary_support;

use productive_composition_canary_support::{emit, Case, LearnedPredicate};

const NONE: &[LearnedPredicate] = &[];
const KO_OPAQUE: &[LearnedPredicate] = &[LearnedPredicate::KoreanInvestigate];
const EN_OPAQUE: &[LearnedPredicate] = &[LearnedPredicate::EnglishInvestigate];

fn cases() -> Vec<Case> {
    vec![
        case(
            "R45_KO_01",
            "korean_left_shared",
            "캐시를 확인하고 수리해",
            NONE,
            &[("INVESTIGATE", "캐시"), ("REPAIR", "캐시")],
            &["FORWARD"],
            &["SEQUENCE"],
            0,
            2,
            2,
            &["SEQUENCE"],
            Some(true),
            None,
        ),
        case(
            "R45_KO_02",
            "korean_left_shared",
            "보고서를 검토하고 수정해",
            NONE,
            &[("INVESTIGATE", "보고서"), ("REPAIR", "보고서")],
            &["FORWARD"],
            &["SEQUENCE"],
            0,
            2,
            2,
            &["SEQUENCE"],
            Some(true),
            None,
        ),
        case(
            "R45_KO_03",
            "korean_left_shared",
            "프로젝트를 분석하고 문서화해",
            NONE,
            &[("INVESTIGATE", "프로젝트"), ("CREATE", "프로젝트")],
            &["FORWARD"],
            &["SEQUENCE"],
            0,
            2,
            2,
            &["SEQUENCE"],
            Some(true),
            None,
        ),
        case(
            "R45_KO_04",
            "korean_left_chain",
            "파일을 읽고 변환하고 저장해",
            NONE,
            &[
                ("EXECUTE", "파일"),
                ("EXECUTE", "파일"),
                ("EXECUTE", "파일"),
            ],
            &["FORWARD", "FORWARD"],
            &["SEQUENCE", "SEQUENCE"],
            0,
            3,
            3,
            &["SEQUENCE", "SEQUENCE"],
            Some(true),
            None,
        ),
        case(
            "R45_KO_05",
            "korean_quantified_shared",
            "모든 파일을 검사하고 수리해",
            NONE,
            &[("INVESTIGATE", "파일"), ("REPAIR", "파일")],
            &["FORWARD"],
            &["SEQUENCE"],
            0,
            2,
            2,
            &["SEQUENCE"],
            Some(true),
            Some("ALL"),
        ),
        case(
            "R45_KO_06",
            "korean_negated_shared",
            "캐시를 확인하고 삭제하지 마",
            NONE,
            &[("INVESTIGATE", "캐시"), ("DELETE", "캐시")],
            &["FORWARD"],
            &["SEQUENCE"],
            1,
            1,
            0,
            &[],
            Some(true),
            None,
        ),
        case(
            "R45_KO_07",
            "korean_cross_intent",
            "코드를 검증하고 배포해",
            NONE,
            &[("INVESTIGATE", "코드"), ("DEPLOY", "코드")],
            &["FORWARD"],
            &["SEQUENCE"],
            0,
            2,
            2,
            &["SEQUENCE"],
            Some(true),
            None,
        ),
        case(
            "R45_KO_08",
            "korean_opaque_productivity",
            "캐시를 무루하고 수리해",
            KO_OPAQUE,
            &[("INVESTIGATE", "캐시"), ("REPAIR", "캐시")],
            &["FORWARD"],
            &["SEQUENCE"],
            0,
            2,
            2,
            &["SEQUENCE"],
            Some(true),
            None,
        ),
        case(
            "R45_EN_01",
            "english_right_shared",
            "Inspect and repair the cache.",
            NONE,
            &[("INVESTIGATE", "cache"), ("REPAIR", "cache")],
            &["BACKWARD"],
            &["COORDINATION"],
            0,
            2,
            2,
            &["COORDINATION"],
            Some(true),
            None,
        ),
        case(
            "R45_EN_02",
            "english_right_shared",
            "Review and correct the report.",
            NONE,
            &[("INVESTIGATE", "report"), ("REPAIR", "report")],
            &["BACKWARD"],
            &["COORDINATION"],
            0,
            2,
            2,
            &["COORDINATION"],
            Some(true),
            None,
        ),
        case(
            "R45_EN_03",
            "english_right_shared",
            "Analyze and document the project.",
            NONE,
            &[("INVESTIGATE", "project"), ("CREATE", "project")],
            &["BACKWARD"],
            &["COORDINATION"],
            0,
            2,
            2,
            &["COORDINATION"],
            Some(true),
            None,
        ),
        case(
            "R45_EN_04",
            "english_right_chain",
            "Read, transform, and save the file.",
            NONE,
            &[
                ("EXECUTE", "file"),
                ("EXECUTE", "file"),
                ("EXECUTE", "file"),
            ],
            &["BACKWARD", "BACKWARD"],
            &["COORDINATION", "COORDINATION"],
            0,
            3,
            3,
            &["COORDINATION", "COORDINATION"],
            Some(true),
            None,
        ),
        case(
            "R45_EN_05",
            "english_negated_shared",
            "Inspect and do not delete the cache.",
            NONE,
            &[("INVESTIGATE", "cache"), ("DELETE", "cache")],
            &["BACKWARD"],
            &["COORDINATION"],
            1,
            1,
            0,
            &[],
            Some(true),
            None,
        ),
        case(
            "R45_EN_06",
            "english_quantified_shared",
            "Verify and deploy every service.",
            NONE,
            &[("INVESTIGATE", "service"), ("DEPLOY", "service")],
            &["BACKWARD"],
            &["COORDINATION"],
            0,
            2,
            2,
            &["COORDINATION"],
            Some(true),
            Some("ALL"),
        ),
        case(
            "R45_EN_07",
            "english_cross_intent",
            "Open and restore the repository.",
            NONE,
            &[("EXECUTE", "repository"), ("REPAIR", "repository")],
            &["BACKWARD"],
            &["COORDINATION"],
            0,
            2,
            2,
            &["COORDINATION"],
            Some(true),
            None,
        ),
        case(
            "R45_EN_08",
            "english_opaque_productivity",
            "Nexel and repair the cache.",
            EN_OPAQUE,
            &[("INVESTIGATE", "cache"), ("REPAIR", "cache")],
            &["BACKWARD"],
            &["COORDINATION"],
            0,
            2,
            2,
            &["COORDINATION"],
            Some(true),
            None,
        ),
        case(
            "R45_BOUNDARY_01",
            "explicit_distinct_arguments",
            "캐시를 확인하고 인덱스를 수리해",
            NONE,
            &[("INVESTIGATE", "캐시"), ("REPAIR", "인덱스")],
            &[],
            &[],
            0,
            2,
            2,
            &["SEQUENCE"],
            Some(false),
            None,
        ),
        case(
            "R45_BOUNDARY_02",
            "explicit_distinct_arguments",
            "Inspect the cache and repair the index.",
            NONE,
            &[("INVESTIGATE", "cache"), ("REPAIR", "index")],
            &[],
            &[],
            0,
            2,
            2,
            &["COORDINATION"],
            Some(false),
            None,
        ),
        case(
            "R45_BOUNDARY_03",
            "explicit_distinct_arguments",
            "입력 파일을 읽고 출력 파일을 저장해",
            NONE,
            &[("EXECUTE", "입력 파일"), ("EXECUTE", "출력 파일")],
            &[],
            &[],
            0,
            2,
            2,
            &["SEQUENCE"],
            Some(false),
            None,
        ),
        case(
            "R45_BOUNDARY_04",
            "explicit_distinct_arguments",
            "Read the input file and save the output file.",
            NONE,
            &[("EXECUTE", "input file"), ("EXECUTE", "output file")],
            &[],
            &[],
            0,
            2,
            2,
            &["COORDINATION"],
            Some(false),
            None,
        ),
        case(
            "R45_BOUNDARY_05",
            "quoted_shared_no_authority",
            "\"캐시를 확인하고 수리해\"라고 사용자가 말했다.",
            NONE,
            &[("INVESTIGATE", "캐시"), ("REPAIR", "캐시")],
            &["FORWARD"],
            &["SEQUENCE"],
            0,
            0,
            0,
            &[],
            Some(true),
            None,
        ),
        case(
            "R45_BOUNDARY_06",
            "quoted_shared_no_authority",
            "The user said \"inspect and repair the cache.\"",
            NONE,
            &[("INVESTIGATE", "cache"), ("REPAIR", "cache")],
            &["BACKWARD"],
            &["COORDINATION"],
            0,
            0,
            0,
            &[],
            Some(true),
            None,
        ),
        case(
            "R45_BOUNDARY_07",
            "condition_does_not_share",
            "캐시를 확인하면 인덱스를 수리해",
            NONE,
            &[("INVESTIGATE", "캐시"), ("REPAIR", "인덱스")],
            &[],
            &[],
            0,
            1,
            0,
            &[],
            Some(false),
            None,
        ),
        case(
            "R45_BOUNDARY_08",
            "condition_does_not_share",
            "If you inspect the cache, repair the index.",
            NONE,
            &[("INVESTIGATE", "cache"), ("REPAIR", "index")],
            &[],
            &[],
            0,
            1,
            0,
            &[],
            Some(false),
            None,
        ),
        case(
            "R45_PRODUCTIVE_01",
            "korean_three_predicates",
            "모든 보고서를 검토하고 수정하고 문서화해",
            NONE,
            &[
                ("INVESTIGATE", "보고서"),
                ("REPAIR", "보고서"),
                ("CREATE", "보고서"),
            ],
            &["FORWARD", "FORWARD"],
            &["SEQUENCE", "SEQUENCE"],
            0,
            3,
            3,
            &["SEQUENCE", "SEQUENCE"],
            Some(true),
            Some("ALL"),
        ),
        case(
            "R45_PRODUCTIVE_02",
            "english_three_predicates",
            "Analyze, summarize, and document every log.",
            NONE,
            &[
                ("INVESTIGATE", "log"),
                ("INVESTIGATE", "log"),
                ("CREATE", "log"),
            ],
            &["BACKWARD", "BACKWARD"],
            &["COORDINATION", "COORDINATION"],
            0,
            3,
            3,
            &["COORDINATION", "COORDINATION"],
            Some(true),
            Some("ALL"),
        ),
        case(
            "R45_PRODUCTIVE_03",
            "korean_intent_reentry",
            "캐시를 검사하고 복구하고 검증해",
            NONE,
            &[
                ("INVESTIGATE", "캐시"),
                ("REPAIR", "캐시"),
                ("INVESTIGATE", "캐시"),
            ],
            &["FORWARD", "FORWARD"],
            &["SEQUENCE", "SEQUENCE"],
            0,
            3,
            3,
            &["SEQUENCE", "SEQUENCE"],
            Some(true),
            None,
        ),
        case(
            "R45_PRODUCTIVE_04",
            "english_intent_reentry",
            "Check, restore, and verify the cache.",
            NONE,
            &[
                ("INVESTIGATE", "cache"),
                ("REPAIR", "cache"),
                ("INVESTIGATE", "cache"),
            ],
            &["BACKWARD", "BACKWARD"],
            &["COORDINATION", "COORDINATION"],
            0,
            3,
            3,
            &["COORDINATION", "COORDINATION"],
            Some(true),
            None,
        ),
    ]
}

#[allow(clippy::too_many_arguments)]
fn case(
    id: &'static str,
    category: &'static str,
    text: &'static str,
    learned: &'static [LearnedPredicate],
    expected_frames: &'static [(&'static str, &'static str)],
    directions: &'static [&'static str],
    binding_relations: &'static [&'static str],
    blocked: usize,
    authorized: usize,
    goal_nodes: usize,
    goal_relations: &'static [&'static str],
    same_argument: Option<bool>,
    quantifier: Option<&'static str>,
) -> Case {
    Case {
        id,
        category,
        text,
        learned,
        expected_frames,
        expected_binding_directions: directions,
        expected_binding_relations: binding_relations,
        expected_blocked: blocked,
        expected_authorized_frames: authorized,
        expected_goal_nodes: goal_nodes,
        expected_goal_relations: goal_relations,
        expect_same_primary_argument: same_argument,
        expected_quantifier: quantifier,
    }
}

fn main() {
    emit("R45_DIAGNOSTIC", cases());
}
