//! Frozen R45 held-out transfer suite.
//!
//! Do not execute this binary until the diagnostic suite passes. It varies
//! vocabulary, arity, polarity, quantification, explicit argument boundaries,
//! quotation, conditionals, and opaque lexical aliases.

mod productive_composition_canary_support;

use productive_composition_canary_support::{emit, Case, LearnedPredicate};

const NONE: &[LearnedPredicate] = &[];
const KO_REPAIR: &[LearnedPredicate] = &[LearnedPredicate::KoreanRepair];
const EN_REPAIR: &[LearnedPredicate] = &[LearnedPredicate::EnglishRepair];

fn cases() -> Vec<Case> {
    vec![
        case(
            "R45T_KO_01",
            "fresh_korean_pair",
            "서버 설정을 진단하고 수정해",
            NONE,
            &[("INVESTIGATE", "서버 설정"), ("REPAIR", "서버 설정")],
            &["FORWARD"],
            &["SEQUENCE"],
            0,
            2,
            2,
            &["SEQUENCE"],
            Some(true),
            None,
        ),
        case(
            "R45T_KO_02",
            "fresh_korean_chain",
            "소스 코드를 검토하고 고치고 검증해",
            NONE,
            &[
                ("INVESTIGATE", "소스 코드"),
                ("REPAIR", "소스 코드"),
                ("INVESTIGATE", "소스 코드"),
            ],
            &["FORWARD", "FORWARD"],
            &["SEQUENCE", "SEQUENCE"],
            0,
            3,
            3,
            &["SEQUENCE", "SEQUENCE"],
            Some(true),
            None,
        ),
        case(
            "R45T_KO_03",
            "fresh_korean_quantifier",
            "각 문서를 분석하고 요약해",
            NONE,
            &[("INVESTIGATE", "문서"), ("INVESTIGATE", "문서")],
            &["FORWARD"],
            &["SEQUENCE"],
            0,
            2,
            2,
            &["SEQUENCE"],
            Some(true),
            Some("EACH"),
        ),
        case(
            "R45T_KO_04",
            "fresh_korean_negation",
            "백업을 확인하고 지우지 마",
            NONE,
            &[("INVESTIGATE", "백업"), ("DELETE", "백업")],
            &["FORWARD"],
            &["SEQUENCE"],
            1,
            1,
            0,
            &[],
            Some(true),
            None,
        ),
        case(
            "R45T_KO_05",
            "fresh_korean_cross_intent",
            "아카이브를 열어보고 복구해",
            NONE,
            &[("EXECUTE", "아카이브"), ("REPAIR", "아카이브")],
            &["FORWARD"],
            &["SEQUENCE"],
            0,
            2,
            2,
            &["SEQUENCE"],
            Some(true),
            None,
        ),
        case(
            "R45T_KO_06",
            "fresh_korean_opaque",
            "파서를 검사하고 가람해",
            KO_REPAIR,
            &[("INVESTIGATE", "파서"), ("REPAIR", "파서")],
            &["FORWARD"],
            &["SEQUENCE"],
            0,
            2,
            2,
            &["SEQUENCE"],
            Some(true),
            None,
        ),
        case(
            "R45T_EN_01",
            "fresh_english_pair",
            "Diagnose and fix the parser.",
            NONE,
            &[("INVESTIGATE", "parser"), ("REPAIR", "parser")],
            &["BACKWARD"],
            &["COORDINATION"],
            0,
            2,
            2,
            &["COORDINATION"],
            Some(true),
            None,
        ),
        case(
            "R45T_EN_02",
            "fresh_english_pair",
            "Examine and restore the archive.",
            NONE,
            &[("INVESTIGATE", "archive"), ("REPAIR", "archive")],
            &["BACKWARD"],
            &["COORDINATION"],
            0,
            2,
            2,
            &["COORDINATION"],
            Some(true),
            None,
        ),
        case(
            "R45T_EN_03",
            "fresh_english_quantifier",
            "Compare and document every result.",
            NONE,
            &[("INVESTIGATE", "result"), ("CREATE", "result")],
            &["BACKWARD"],
            &["COORDINATION"],
            0,
            2,
            2,
            &["COORDINATION"],
            Some(true),
            Some("ALL"),
        ),
        case(
            "R45T_EN_04",
            "fresh_english_negation",
            "Review and do not remove the stale file.",
            NONE,
            &[("INVESTIGATE", "stale file"), ("DELETE", "stale file")],
            &["BACKWARD"],
            &["COORDINATION"],
            1,
            1,
            0,
            &[],
            Some(true),
            None,
        ),
        case(
            "R45T_EN_05",
            "fresh_english_chain",
            "Open, convert, and save each document.",
            NONE,
            &[
                ("EXECUTE", "document"),
                ("EXECUTE", "document"),
                ("EXECUTE", "document"),
            ],
            &["BACKWARD", "BACKWARD"],
            &["COORDINATION", "COORDINATION"],
            0,
            3,
            3,
            &["COORDINATION", "COORDINATION"],
            Some(true),
            Some("EACH"),
        ),
        case(
            "R45T_EN_06",
            "fresh_english_opaque",
            "Inspect and vorda the worker.",
            EN_REPAIR,
            &[("INVESTIGATE", "worker"), ("REPAIR", "worker")],
            &["BACKWARD"],
            &["COORDINATION"],
            0,
            2,
            2,
            &["COORDINATION"],
            Some(true),
            None,
        ),
        case(
            "R45T_BOUNDARY_01",
            "fresh_distinct_arguments",
            "서버를 확인하고 클라이언트를 수정해",
            NONE,
            &[("INVESTIGATE", "서버"), ("REPAIR", "클라이언트")],
            &[],
            &[],
            0,
            2,
            2,
            &["SEQUENCE"],
            Some(false),
            None,
        ),
        case(
            "R45T_BOUNDARY_02",
            "fresh_distinct_arguments",
            "Diagnose the server and fix the client.",
            NONE,
            &[("INVESTIGATE", "server"), ("REPAIR", "client")],
            &[],
            &[],
            0,
            2,
            2,
            &["COORDINATION"],
            Some(false),
            None,
        ),
        case(
            "R45T_BOUNDARY_03",
            "conditional_nonsharing",
            "로그를 분석하면 보고서를 작성해",
            NONE,
            &[("INVESTIGATE", "로그"), ("CREATE", "보고서")],
            &[],
            &[],
            0,
            1,
            0,
            &[],
            Some(false),
            None,
        ),
        case(
            "R45T_BOUNDARY_04",
            "conditional_nonsharing",
            "If you analyze the log, create the report.",
            NONE,
            &[("INVESTIGATE", "log"), ("CREATE", "report")],
            &[],
            &[],
            0,
            1,
            0,
            &[],
            Some(false),
            None,
        ),
        case(
            "R45T_BOUNDARY_05",
            "explicit_repetition",
            "캐시를 확인하고 캐시를 수리해",
            NONE,
            &[("INVESTIGATE", "캐시"), ("REPAIR", "캐시")],
            &[],
            &[],
            0,
            2,
            2,
            &["SEQUENCE"],
            Some(false),
            None,
        ),
        case(
            "R45T_BOUNDARY_06",
            "explicit_repetition",
            "Inspect the cache and repair the cache.",
            NONE,
            &[("INVESTIGATE", "cache"), ("REPAIR", "cache")],
            &[],
            &[],
            0,
            2,
            2,
            &["COORDINATION"],
            Some(false),
            None,
        ),
        case(
            "R45T_BOUNDARY_07",
            "quoted_no_authority",
            "Alice repeated: \"diagnose and fix the parser.\"",
            NONE,
            &[("INVESTIGATE", "parser"), ("REPAIR", "parser")],
            &["BACKWARD"],
            &["COORDINATION"],
            0,
            0,
            0,
            &[],
            Some(true),
            None,
        ),
        case(
            "R45T_PRODUCTIVE_01",
            "contrastive_shared_negation",
            "Inspect but do not repair the cache.",
            NONE,
            &[("INVESTIGATE", "cache"), ("REPAIR", "cache")],
            &["BACKWARD"],
            &["CONTRAST"],
            1,
            1,
            0,
            &[],
            Some(true),
            None,
        ),
    ]
}

#[allow(clippy::too_many_arguments)]
fn case(
    id: &'static str,
    category: &'static str,
    text: &'static str,
    learned: &'static [LearnedPredicate],
    expected_frames: &'static [(&'static str, &'static str)],
    directions: &'static [&'static str],
    binding_relations: &'static [&'static str],
    blocked: usize,
    authorized: usize,
    goal_nodes: usize,
    goal_relations: &'static [&'static str],
    same_argument: Option<bool>,
    quantifier: Option<&'static str>,
) -> Case {
    Case {
        id,
        category,
        text,
        learned,
        expected_frames,
        expected_binding_directions: directions,
        expected_binding_relations: binding_relations,
        expected_blocked: blocked,
        expected_authorized_frames: authorized,
        expected_goal_nodes: goal_nodes,
        expected_goal_relations: goal_relations,
        expect_same_primary_argument: same_argument,
        expected_quantifier: quantifier,
    }
}

fn main() {
    emit("R45_TRANSFER", cases());
}
