//! Frozen R57 first-exposure transfer suite. Surfaces and topic/focus pairings
//! are disjoint from the repair diagnostic and are executed only after freeze.

mod topic_context_consolidation_canary_support;

use semantic_core_adapters::LanguageCodeIR::{English, Korean};
use topic_context_consolidation_canary_support::{emit, text, voice, Case};

const CASES: &[Case] = &[
    Case {
        id: "R57_H01",
        category: "english_previous_topic_local_code_focus",
        turns: &[
            text("Switch to server.", English),
            text("Analyze the code.", English),
            text("Switch to backup.", English),
            text("Inspect the document.", English),
            text("Return to the previous topic.", English),
            text("Repair it.", English),
        ],
        restoration_turn: 5,
        expected_topic: "server",
        expected_focus: "code",
        forbidden_focuses: &["document", "backup"],
        expected_transition: "RESUME",
        require_pending_question: false,
    },
    Case {
        id: "R57_H02",
        category: "korean_previous_topic_local_report_focus",
        turns: &[
            text("로그 주제로 전환해.", Korean),
            text("보고서를 분석해.", Korean),
            text("워커 주제로 전환해.", Korean),
            text("파일을 검사해.", Korean),
            text("이전 주제로 돌아가.", Korean),
            text("그것을 수리해.", Korean),
        ],
        restoration_turn: 5,
        expected_topic: "로그",
        expected_focus: "보고서",
        forbidden_focuses: &["파일", "워커"],
        expected_transition: "RESUME",
        require_pending_question: false,
    },
    Case {
        id: "R57_H03",
        category: "cross_language_three_topic_indexed_resume",
        turns: &[
            text("프로젝트 주제로 전환해.", Korean),
            text("저장소를 검사해.", Korean),
            text("Switch to server.", English),
            text("Analyze the file.", English),
            text("백업 주제로 전환해.", Korean),
            text("문서를 검사해.", Korean),
            text("Return to the topic two topics ago.", English),
            text("Repair it.", English),
        ],
        restoration_turn: 7,
        expected_topic: "project",
        expected_focus: "저장소",
        forbidden_focuses: &["file", "document", "backup"],
        expected_transition: "RESUME",
        require_pending_question: false,
    },
    Case {
        id: "R57_H04",
        category: "hesitation_does_not_replace_local_focus",
        turns: &[
            text("Switch to log.", English),
            text("Inspect the repository.", English),
            text("Switch to worker.", English),
            text("Analyze the project.", English),
            text("Uh, one moment.", English),
            text("Return to log.", English),
            text("Repair it.", English),
        ],
        restoration_turn: 6,
        expected_topic: "log",
        expected_focus: "repository",
        forbidden_focuses: &["project", "worker"],
        expected_transition: "RESUME",
        require_pending_question: false,
    },
    Case {
        id: "R57_H05",
        category: "cross_language_qud_common_focus_resume",
        turns: &[
            text("문서 주제로 전환해.", Korean),
            voice("프로젝트를 검사해.", "프로젝트를 수리해.", Korean),
            text("Switch to queue.", English),
            text("Analyze the folder.", English),
            text("Return to document.", English),
            text("The second one.", English),
        ],
        restoration_turn: 5,
        expected_topic: "document",
        expected_focus: "project",
        forbidden_focuses: &["folder", "queue"],
        expected_transition: "RESUME",
        require_pending_question: true,
    },
    Case {
        id: "R57_H06",
        category: "fresh_backup_topic_has_no_borrowed_focus",
        turns: &[
            text("Switch to worker.", English),
            text("Inspect the repository.", English),
            text("Switch to backup.", English),
            text("Analyze it.", English),
        ],
        restoration_turn: 3,
        expected_topic: "backup",
        expected_focus: "backup",
        forbidden_focuses: &["repository", "worker"],
        expected_transition: "ACTIVATE",
        require_pending_question: false,
    },
    Case {
        id: "R57_H07",
        category: "korean_coordinated_local_nucleus_resume",
        turns: &[
            text("서버 주제로 전환해.", Korean),
            text("파일을 검사하고 저장소를 수리해.", Korean),
            text("백업 주제로 전환해.", Korean),
            text("문서를 검사하고 프로젝트를 분석해.", Korean),
            text("서버 주제로 돌아가.", Korean),
            text("그것을 검사해.", Korean),
        ],
        restoration_turn: 5,
        expected_topic: "서버",
        expected_focus: "저장소",
        forbidden_focuses: &["프로젝트", "백업"],
        expected_transition: "RESUME",
        require_pending_question: false,
    },
    Case {
        id: "R57_H08",
        category: "long_cross_language_resume_after_social_turns",
        turns: &[
            text("Switch to report.", English),
            text("Analyze the folder.", English),
            text("캐시 주제로 전환해.", Korean),
            text("파일을 검사해.", Korean),
            text("음, 잠깐만.", Korean),
            text("응.", Korean),
            text("Return to report.", English),
            text("Repair it.", English),
        ],
        restoration_turn: 7,
        expected_topic: "report",
        expected_focus: "folder",
        forbidden_focuses: &["file", "cache"],
        expected_transition: "RESUME",
        require_pending_question: false,
    },
];

fn main() {
    emit(
        "R57_TOPIC_CONTEXT_CONSOLIDATION_FIRST_EXPOSURE_TRANSFER",
        CASES,
    );
}
