//! Frozen R57 diagnostic for topic-local discourse focus and state consolidation.
//! Cases are structural compositions over topics, focus, QUD, language, and delay.

mod topic_context_consolidation_canary_support;

use semantic_core_adapters::LanguageCodeIR::{English, Korean};
use topic_context_consolidation_canary_support::{emit, text, voice, Case};

const CASES: &[Case] = &[
    Case {
        id: "R57_01",
        category: "english_named_topic_restores_local_focus",
        turns: &[
            text("Switch to cache.", English),
            text("Inspect the file.", English),
            text("Switch to queue.", English),
            text("Inspect the folder.", English),
            text("Return to cache.", English),
            text("Repair it.", English),
        ],
        restoration_turn: 5,
        expected_topic: "cache",
        expected_focus: "file",
        forbidden_focuses: &["folder", "queue"],
        expected_transition: "RESUME",
        require_pending_question: false,
    },
    Case {
        id: "R57_02",
        category: "korean_named_topic_restores_local_focus",
        turns: &[
            text("캐시 주제로 전환해.", Korean),
            text("파일을 검사해.", Korean),
            text("큐 주제로 전환해.", Korean),
            text("폴더를 검사해.", Korean),
            text("캐시 주제로 돌아가.", Korean),
            text("그것을 수리해.", Korean),
        ],
        restoration_turn: 5,
        expected_topic: "캐시",
        expected_focus: "파일",
        forbidden_focuses: &["폴더", "큐"],
        expected_transition: "RESUME",
        require_pending_question: false,
    },
    Case {
        id: "R57_03",
        category: "korean_context_english_return",
        turns: &[
            text("캐시 주제로 전환해.", Korean),
            text("문서를 분석해.", Korean),
            text("Switch to worker.", English),
            text("Inspect the report.", English),
            text("Return to cache.", English),
            text("Repair it.", English),
        ],
        restoration_turn: 5,
        expected_topic: "cache",
        expected_focus: "문서",
        forbidden_focuses: &["report", "worker"],
        expected_transition: "RESUME",
        require_pending_question: false,
    },
    Case {
        id: "R57_04",
        category: "english_context_korean_return",
        turns: &[
            text("Switch to backup.", English),
            text("Inspect the repository.", English),
            text("로그 주제로 전환해.", Korean),
            text("프로젝트를 분석해.", Korean),
            text("백업 주제로 돌아가.", Korean),
            text("그것을 수리해.", Korean),
        ],
        restoration_turn: 5,
        expected_topic: "백업",
        expected_focus: "repository",
        forbidden_focuses: &["프로젝트", "로그"],
        expected_transition: "RESUME",
        require_pending_question: false,
    },
    Case {
        id: "R57_05",
        category: "english_indexed_three_topic_resume",
        turns: &[
            text("Switch to cache.", English),
            text("Inspect the file.", English),
            text("Switch to queue.", English),
            text("Inspect the folder.", English),
            text("Switch to log.", English),
            text("Inspect the report.", English),
            text("Return to the topic two topics ago.", English),
            text("Repair it.", English),
        ],
        restoration_turn: 7,
        expected_topic: "cache",
        expected_focus: "file",
        forbidden_focuses: &["folder", "report", "log"],
        expected_transition: "RESUME",
        require_pending_question: false,
    },
    Case {
        id: "R57_06",
        category: "korean_indexed_three_topic_resume",
        turns: &[
            text("백업 주제로 전환해.", Korean),
            text("문서를 검사해.", Korean),
            text("서버 주제로 전환해.", Korean),
            text("파일을 분석해.", Korean),
            text("워커 주제로 전환해.", Korean),
            text("폴더를 검사해.", Korean),
            text("두 주제 전으로 돌아가자.", Korean),
            text("그것을 수리해.", Korean),
        ],
        restoration_turn: 7,
        expected_topic: "백업",
        expected_focus: "문서",
        forbidden_focuses: &["파일", "폴더", "워커"],
        expected_transition: "RESUME",
        require_pending_question: false,
    },
    Case {
        id: "R57_07",
        category: "neutral_turns_preserve_suspended_focus",
        turns: &[
            text("Switch to cache.", English),
            text("Analyze the document.", English),
            text("Switch to queue.", English),
            text("Inspect the folder.", English),
            text("Um, let me think.", English),
            text("Right.", English),
            text("Return to cache.", English),
            text("Repair it.", English),
        ],
        restoration_turn: 7,
        expected_topic: "cache",
        expected_focus: "document",
        forbidden_focuses: &["folder", "queue"],
        expected_transition: "RESUME",
        require_pending_question: false,
    },
    Case {
        id: "R57_08",
        category: "coordinated_focus_is_restored_per_topic",
        turns: &[
            text("Switch to cache.", English),
            text("Inspect the file and repair the document.", English),
            text("Switch to queue.", English),
            text("Inspect the folder and repair the report.", English),
            text("Return to cache.", English),
            text("Analyze it.", English),
        ],
        restoration_turn: 5,
        expected_topic: "cache",
        expected_focus: "document",
        forbidden_focuses: &["report", "queue"],
        expected_transition: "RESUME",
        require_pending_question: false,
    },
    Case {
        id: "R57_09",
        category: "english_topic_qud_is_consolidated",
        turns: &[
            text("Switch to cache.", English),
            voice("Inspect the file.", "Repair the file.", English),
            text("Switch to queue.", English),
            text("Inspect the folder.", English),
            text("Return to cache.", English),
            text("The second one.", English),
        ],
        restoration_turn: 5,
        expected_topic: "cache",
        expected_focus: "file",
        forbidden_focuses: &["folder", "queue"],
        expected_transition: "RESUME",
        require_pending_question: true,
    },
    Case {
        id: "R57_10",
        category: "korean_topic_qud_is_consolidated",
        turns: &[
            text("캐시 주제로 전환해.", Korean),
            voice("파일을 검사해.", "파일을 수리해.", Korean),
            text("큐 주제로 전환해.", Korean),
            text("폴더를 검사해.", Korean),
            text("캐시 주제로 돌아가.", Korean),
            text("두 번째.", Korean),
        ],
        restoration_turn: 5,
        expected_topic: "캐시",
        expected_focus: "파일",
        forbidden_focuses: &["폴더", "큐"],
        expected_transition: "RESUME",
        require_pending_question: true,
    },
    Case {
        id: "R57_11",
        category: "unseen_english_topic_does_not_borrow_focus",
        turns: &[
            text("Switch to cache.", English),
            text("Inspect the file.", English),
            text("Switch to report.", English),
            text("Repair it.", English),
        ],
        restoration_turn: 3,
        expected_topic: "report",
        expected_focus: "report",
        forbidden_focuses: &["file", "cache"],
        expected_transition: "ACTIVATE",
        require_pending_question: false,
    },
    Case {
        id: "R57_12",
        category: "unseen_korean_topic_does_not_borrow_focus",
        turns: &[
            text("서버 주제로 전환해.", Korean),
            text("문서를 검사해.", Korean),
            text("프로젝트 주제로 전환해.", Korean),
            text("그것을 수리해.", Korean),
        ],
        restoration_turn: 3,
        expected_topic: "프로젝트",
        expected_focus: "프로젝트",
        forbidden_focuses: &["문서", "서버"],
        expected_transition: "ACTIVATE",
        require_pending_question: false,
    },
];

fn main() {
    emit("R57_TOPIC_CONTEXT_CONSOLIDATION_DIAGNOSTIC", CASES);
}
