//! Frozen R59 diagnostic suite: surface form must not replace communicative intent.

mod utterance_intent_pragmatic_inference_canary_support;

use semantic_core_adapters::LanguageCodeIR;
use utterance_intent_pragmatic_inference_canary_support::{emit, Case};

const CASES: &[Case] = &[
    Case {
        id: "R59_01",
        category: "korean_problem_disclosure",
        setup: None,
        text: "업로드가 계속 중간에 멈추는데.",
        language: LanguageCodeIR::Korean,
        expected_intent: "PROBLEM_DISCLOSURE",
        expected_response: "DIAGNOSIS_OR_NEXT_STEP",
        expected_target_fragment: "업로드",
        expected_goal_intent: Some("INVESTIGATE"),
        expected_speech_act: "ASK",
        expected_constraint_fragment: None,
        forbidden_authorized_predicate: None,
        clarification: false,
    },
    Case {
        id: "R59_02",
        category: "english_problem_disclosure",
        setup: None,
        text: "The upload keeps stopping halfway.",
        language: LanguageCodeIR::English,
        expected_intent: "PROBLEM_DISCLOSURE",
        expected_response: "DIAGNOSIS_OR_NEXT_STEP",
        expected_target_fragment: "upload",
        expected_goal_intent: Some("INVESTIGATE"),
        expected_speech_act: "ASK",
        expected_constraint_fragment: None,
        forbidden_authorized_predicate: None,
        clarification: false,
    },
    Case {
        id: "R59_03",
        category: "korean_readiness_assessment",
        setup: None,
        text: "이 빌드 지금 배포해도 되는 상태야?",
        language: LanguageCodeIR::Korean,
        expected_intent: "ASSESSMENT_REQUEST",
        expected_response: "ASSESSMENT",
        expected_target_fragment: "빌드",
        expected_goal_intent: Some("INVESTIGATE"),
        expected_speech_act: "ASK",
        expected_constraint_fragment: None,
        forbidden_authorized_predicate: Some("DEPLOY"),
        clarification: false,
    },
    Case {
        id: "R59_04",
        category: "english_readiness_assessment",
        setup: None,
        text: "Is this build actually ready to deploy?",
        language: LanguageCodeIR::English,
        expected_intent: "ASSESSMENT_REQUEST",
        expected_response: "ASSESSMENT",
        expected_target_fragment: "build",
        expected_goal_intent: Some("INVESTIGATE"),
        expected_speech_act: "ASK",
        expected_constraint_fragment: None,
        forbidden_authorized_predicate: Some("DEPLOY"),
        clarification: false,
    },
    Case {
        id: "R59_05",
        category: "korean_evidence_request",
        setup: None,
        text: "그 결론을 뒷받침하는 근거는?",
        language: LanguageCodeIR::Korean,
        expected_intent: "EVIDENCE_REQUEST",
        expected_response: "EVIDENCE",
        expected_target_fragment: "결론",
        expected_goal_intent: Some("EXPLAIN"),
        expected_speech_act: "ASK",
        expected_constraint_fragment: None,
        forbidden_authorized_predicate: None,
        clarification: false,
    },
    Case {
        id: "R59_06",
        category: "english_evidence_request",
        setup: None,
        text: "What evidence supports that conclusion?",
        language: LanguageCodeIR::English,
        expected_intent: "EVIDENCE_REQUEST",
        expected_response: "EVIDENCE",
        expected_target_fragment: "conclusion",
        expected_goal_intent: Some("EXPLAIN"),
        expected_speech_act: "ASK",
        expected_constraint_fragment: None,
        forbidden_authorized_predicate: None,
        clarification: false,
    },
    Case {
        id: "R59_07",
        category: "korean_recommendation_request",
        setup: None,
        text: "캐시 삭제와 우회 경로 중 뭐가 더 안전해?",
        language: LanguageCodeIR::Korean,
        expected_intent: "RECOMMENDATION_REQUEST",
        expected_response: "RECOMMENDATION",
        expected_target_fragment: "캐시",
        expected_goal_intent: Some("PLAN"),
        expected_speech_act: "ASK",
        expected_constraint_fragment: Some("safe"),
        forbidden_authorized_predicate: Some("DELETE"),
        clarification: false,
    },
    Case {
        id: "R59_08",
        category: "english_recommendation_request",
        setup: None,
        text: "Which is safer, deleting the cache or using a bypass?",
        language: LanguageCodeIR::English,
        expected_intent: "RECOMMENDATION_REQUEST",
        expected_response: "RECOMMENDATION",
        expected_target_fragment: "cache",
        expected_goal_intent: Some("PLAN"),
        expected_speech_act: "ASK",
        expected_constraint_fragment: Some("safe"),
        forbidden_authorized_predicate: Some("DELETE"),
        clarification: false,
    },
    Case {
        id: "R59_09",
        category: "korean_response_goal_correction",
        setup: Some("로그를 검사해줘."),
        text: "아니, 로그를 검사하라는 게 아니라 왜 실패했는지 설명해달라는 거야.",
        language: LanguageCodeIR::Korean,
        expected_intent: "RESPONSE_GOAL_CORRECTION",
        expected_response: "EXPLANATION",
        expected_target_fragment: "실패",
        expected_goal_intent: Some("EXPLAIN"),
        expected_speech_act: "ASK",
        expected_constraint_fragment: Some("replace"),
        forbidden_authorized_predicate: Some("INVESTIGATE"),
        clarification: false,
    },
    Case {
        id: "R59_10",
        category: "english_response_goal_correction",
        setup: Some("Inspect the log."),
        text: "No, I am not asking you to inspect it; explain why it failed.",
        language: LanguageCodeIR::English,
        expected_intent: "RESPONSE_GOAL_CORRECTION",
        expected_response: "EXPLANATION",
        expected_target_fragment: "failed",
        expected_goal_intent: Some("EXPLAIN"),
        expected_speech_act: "ASK",
        expected_constraint_fragment: Some("replace"),
        forbidden_authorized_predicate: Some("INVESTIGATE"),
        clarification: false,
    },
    Case {
        id: "R59_11",
        category: "korean_summary_request",
        setup: Some("캐시와 큐의 상태를 비교해줘."),
        text: "그래서 결론은?",
        language: LanguageCodeIR::Korean,
        expected_intent: "SUMMARY_REQUEST",
        expected_response: "SUMMARY",
        expected_target_fragment: "캐시",
        expected_goal_intent: Some("EXPLAIN"),
        expected_speech_act: "ASK",
        expected_constraint_fragment: None,
        forbidden_authorized_predicate: None,
        clarification: false,
    },
    Case {
        id: "R59_12",
        category: "english_summary_request",
        setup: Some("Compare the cache and queue state."),
        text: "So what is the bottom line?",
        language: LanguageCodeIR::English,
        expected_intent: "SUMMARY_REQUEST",
        expected_response: "SUMMARY",
        expected_target_fragment: "cache",
        expected_goal_intent: Some("EXPLAIN"),
        expected_speech_act: "ASK",
        expected_constraint_fragment: None,
        forbidden_authorized_predicate: None,
        clarification: false,
    },
    Case {
        id: "R59_13",
        category: "korean_conditional_decision",
        setup: None,
        text: "통합이 실제 커버리지를 넓힌다면 힘들어도 계속할 만해.",
        language: LanguageCodeIR::Korean,
        expected_intent: "CONDITIONAL_DECISION_REQUEST",
        expected_response: "VERIFY_THEN_DECIDE",
        expected_target_fragment: "통합",
        expected_goal_intent: Some("INVESTIGATE"),
        expected_speech_act: "CONDITIONALCONTINUATION",
        expected_constraint_fragment: Some("커버리지"),
        forbidden_authorized_predicate: Some("CONTINUE"),
        clarification: false,
    },
    Case {
        id: "R59_14",
        category: "english_conditional_decision",
        setup: None,
        text: "If the integration truly expands coverage, it is worth continuing despite the cost.",
        language: LanguageCodeIR::English,
        expected_intent: "CONDITIONAL_DECISION_REQUEST",
        expected_response: "VERIFY_THEN_DECIDE",
        expected_target_fragment: "integration",
        expected_goal_intent: Some("INVESTIGATE"),
        expected_speech_act: "CONDITIONALCONTINUATION",
        expected_constraint_fragment: Some("coverage"),
        forbidden_authorized_predicate: Some("CONTINUE"),
        clarification: false,
    },
    Case {
        id: "R59_15",
        category: "korean_preservation_constrained_recommendation",
        setup: None,
        text: "원본 데이터는 절대 잃으면 안 돼. 어떤 복구 방법이 제일 나아?",
        language: LanguageCodeIR::Korean,
        expected_intent: "RECOMMENDATION_REQUEST",
        expected_response: "RECOMMENDATION",
        expected_target_fragment: "복구",
        expected_goal_intent: Some("PLAN"),
        expected_speech_act: "ASK",
        expected_constraint_fragment: Some("preserve"),
        forbidden_authorized_predicate: Some("DELETE"),
        clarification: false,
    },
    Case {
        id: "R59_16",
        category: "english_preservation_constrained_recommendation",
        setup: None,
        text: "I cannot lose the original data. Which recovery approach is best?",
        language: LanguageCodeIR::English,
        expected_intent: "RECOMMENDATION_REQUEST",
        expected_response: "RECOMMENDATION",
        expected_target_fragment: "recovery",
        expected_goal_intent: Some("PLAN"),
        expected_speech_act: "ASK",
        expected_constraint_fragment: Some("preserve"),
        forbidden_authorized_predicate: Some("DELETE"),
        clarification: false,
    },
];

fn main() {
    emit(
        "R59_UTTERANCE_INTENT_PRAGMATIC_INFERENCE_DIAGNOSTIC",
        false,
        CASES,
    );
}
