//! Frozen R59 held-out transfer suite. Do not run before the diagnostic passes.

mod utterance_intent_pragmatic_inference_canary_support;

use semantic_core_adapters::LanguageCodeIR;
use utterance_intent_pragmatic_inference_canary_support::{emit, Case};

const CASES: &[Case] = &[
    Case {
        id: "R59_H01",
        category: "korean_idiomatic_problem_disclosure",
        setup: None,
        text: "동기화가 또 끝에서 멎네.",
        language: LanguageCodeIR::Korean,
        expected_intent: "PROBLEM_DISCLOSURE",
        expected_response: "DIAGNOSIS_OR_NEXT_STEP",
        expected_target_fragment: "동기화",
        expected_goal_intent: Some("INVESTIGATE"),
        expected_speech_act: "ASK",
        expected_constraint_fragment: None,
        forbidden_authorized_predicate: None,
        clarification: false,
    },
    Case {
        id: "R59_H02",
        category: "english_idiomatic_problem_disclosure",
        setup: None,
        text: "The export dies at the last step again.",
        language: LanguageCodeIR::English,
        expected_intent: "PROBLEM_DISCLOSURE",
        expected_response: "DIAGNOSIS_OR_NEXT_STEP",
        expected_target_fragment: "export",
        expected_goal_intent: Some("INVESTIGATE"),
        expected_speech_act: "ASK",
        expected_constraint_fragment: None,
        forbidden_authorized_predicate: None,
        clarification: false,
    },
    Case {
        id: "R59_H03",
        category: "korean_readiness_transfer",
        setup: None,
        text: "이 정도면 운영에 올려도 괜찮은 거야?",
        language: LanguageCodeIR::Korean,
        expected_intent: "ASSESSMENT_REQUEST",
        expected_response: "ASSESSMENT",
        expected_target_fragment: "운영",
        expected_goal_intent: Some("INVESTIGATE"),
        expected_speech_act: "ASK",
        expected_constraint_fragment: None,
        forbidden_authorized_predicate: Some("DEPLOY"),
        clarification: false,
    },
    Case {
        id: "R59_H04",
        category: "english_readiness_transfer",
        setup: None,
        text: "Can this release safely go live now?",
        language: LanguageCodeIR::English,
        expected_intent: "ASSESSMENT_REQUEST",
        expected_response: "ASSESSMENT",
        expected_target_fragment: "release",
        expected_goal_intent: Some("INVESTIGATE"),
        expected_speech_act: "ASK",
        expected_constraint_fragment: None,
        forbidden_authorized_predicate: Some("DEPLOY"),
        clarification: false,
    },
    Case {
        id: "R59_H05",
        category: "korean_evidence_transfer",
        setup: None,
        text: "그 판단을 믿을 만한 증거가 있어?",
        language: LanguageCodeIR::Korean,
        expected_intent: "EVIDENCE_REQUEST",
        expected_response: "EVIDENCE",
        expected_target_fragment: "판단",
        expected_goal_intent: Some("EXPLAIN"),
        expected_speech_act: "ASK",
        expected_constraint_fragment: None,
        forbidden_authorized_predicate: None,
        clarification: false,
    },
    Case {
        id: "R59_H06",
        category: "english_evidence_transfer",
        setup: None,
        text: "What backs up that recommendation?",
        language: LanguageCodeIR::English,
        expected_intent: "EVIDENCE_REQUEST",
        expected_response: "EVIDENCE",
        expected_target_fragment: "recommendation",
        expected_goal_intent: Some("EXPLAIN"),
        expected_speech_act: "ASK",
        expected_constraint_fragment: None,
        forbidden_authorized_predicate: None,
        clarification: false,
    },
    Case {
        id: "R59_H07",
        category: "korean_response_goal_correction_transfer",
        setup: Some("테스트를 다시 실행해줘."),
        text: "재실행해달라는 말이 아니야. 실패 원인만 설명해줘.",
        language: LanguageCodeIR::Korean,
        expected_intent: "RESPONSE_GOAL_CORRECTION",
        expected_response: "EXPLANATION",
        expected_target_fragment: "실패",
        expected_goal_intent: Some("EXPLAIN"),
        expected_speech_act: "ASK",
        expected_constraint_fragment: Some("replace"),
        forbidden_authorized_predicate: Some("EXECUTE"),
        clarification: false,
    },
    Case {
        id: "R59_H08",
        category: "english_response_goal_correction_transfer",
        setup: Some("Rerun the test."),
        text: "I was not asking for another run; just explain the cause of the failure.",
        language: LanguageCodeIR::English,
        expected_intent: "RESPONSE_GOAL_CORRECTION",
        expected_response: "EXPLANATION",
        expected_target_fragment: "failure",
        expected_goal_intent: Some("EXPLAIN"),
        expected_speech_act: "ASK",
        expected_constraint_fragment: Some("replace"),
        forbidden_authorized_predicate: Some("EXECUTE"),
        clarification: false,
    },
    Case {
        id: "R59_H09",
        category: "korean_contextless_summary_fail_closed",
        setup: None,
        text: "그래서 핵심만 말하면?",
        language: LanguageCodeIR::Korean,
        expected_intent: "SUMMARY_REQUEST",
        expected_response: "CLARIFICATION",
        expected_target_fragment: "prior discourse",
        expected_goal_intent: None,
        expected_speech_act: "ASK",
        expected_constraint_fragment: Some("context"),
        forbidden_authorized_predicate: None,
        clarification: true,
    },
    Case {
        id: "R59_H10",
        category: "english_contextless_summary_fail_closed",
        setup: None,
        text: "And the takeaway?",
        language: LanguageCodeIR::English,
        expected_intent: "SUMMARY_REQUEST",
        expected_response: "CLARIFICATION",
        expected_target_fragment: "prior discourse",
        expected_goal_intent: None,
        expected_speech_act: "ASK",
        expected_constraint_fragment: Some("context"),
        forbidden_authorized_predicate: None,
        clarification: true,
    },
];

fn main() {
    emit(
        "R59_UTTERANCE_INTENT_PRAGMATIC_INFERENCE_HELDOUT",
        true,
        CASES,
    );
}
